[workspace]
resolver = "3"
members = ["frontend", "middle", "data", "backend", "factory"]

[workspace.lints.rust]
unused_imports = "deny"

[workspace.lints.clippy]
enum_glob_use = { level = "deny", priority = -1 }
pedantic = "deny"
nursery = "deny"
unwrap_used = { level = "deny", priority = -1 }
wildcard_enum_match_arm = { level = "deny", priority = -1 }
match_same_arms = { level = "deny", priority = -1 }
missing_panics_doc = { level = "allow", priority = 1 }
wildcard-enum-match-arm = { level = "allow", priority = 1 }
legacy_numeric_constants = "deny"


[profile.release-with-debug]
inherits = "release"
debug = true
strip = false
lto = false

[profile.release-with-debug-asserts]
inherits = "release"
debug-assertions = true