[package]
name = "middle"
version = "0.1.0"
edition = "2024"

[dependencies]
data = { path = "../data" } 
itertools = "0.14.0"
smallvec = { version = "1.15.2", features = ["serde", "union"] }
stable-vec = "0.4.2"

[dev-dependencies]
proptest = "1.11.0"
data = { path = "../data", features = ["test"] }

[lints]
workspace = true
